### PR TITLE
Fix broken links

### LINKED ISSUE #58: Fix CI
[\*ahem\*](https://travis-ci.org/bluerobotics/bluerobotics.github.io/builds)

### PR DESCRIPTION
**Pull request by jaxxzer**
Fix #58

### CODE REVIEW

**Comment by jaxxzer** [comment]
The first commit here addresses the first failure shown here: https://travis-ci.org/bluerobotics/bluerobotics.github.io/builds/386272848#L676

**Comment by jaxxzer** [comment]
@mariya-bluerobotics I would have preferred the link fixes go in separate commits. As a general rule, I like for a commit to contain changes inside only a single directory. This is not something to hold this PR up, though.

Please rebase and resolve the conflicts :upside_down_face: 

It is a little bit weird that there is a merge commit here. If you are not sure of what you are doing with git, please ask.

**Comment by mariyachanniwala** [comment]
Hey Jacob,

You want me to do every error in a different commit? I am not sure if I understand. Do you want me to do errors in one file in a single commit or like each individual error in different commits?

**Comment by jaxxzer** [comment]
@mariyachanniwala it looks like our rebase uncovered some more CI failures. Please have a look, let me know if they look like things you have already addressed.

**Comment by mariyachanniwala** [comment]
Yeah these are all new issues. Looks like I need to change a few more things. I dont know how that happened though.

**Comment by jaxxzer** [comment]
*magic*

**Comment by jaxxzer** [comment]
Thanks!

**Comment by mariyachanniwala** [comment]
no problem!

**Pull request merged**
