### PR TITLE
Andrew edits

### PR DESCRIPTION
**Pull request by AndrewHou97**
Minor changes. Mainly just things I think should be changed, but not sure if need to/correct. File attached. Let me know what you think!
[doc edits 6-19 (2).txt](https://github.com/bluerobotics/bluerobotics.github.io/files/2117110/doc.edits.6-19.2.txt)

### CODE REVIEW

**Comment by jaxxzer** [comment]
@AndrewHou97 please rebase this and resolve the conflicts. You can ask @mariyachanniwala or @dheideman for help.

**Comment by jaxxzer** [comment]
All good. Ask Mariya for some help to remove it.

**Comment by jaxxzer** [comment]
`git push origin 9c7cb34:Andrew-edits -f`

**Comment by AndrewHou97** [comment]
Mariya helped me fix it :)

**Pull request merged**
