### PR TITLE
Bar30 Arduino Tutorial

### PR DESCRIPTION
**Pull request by dheideman**
Adds a tutorial for communicating with a Bar30 with an Arduino.  The tutorial is located at: [localhost:4000/bar30/bar30-arduino](http://localhost:4000/bar30/bar30-arduino)

state: first draft

To Do:
- annotate images:
  - add "+5 V", "SDA", "SCL", & "GND" labels to jumper cables
  - add arrows to point at menu items

### CODE REVIEW

**Comment by kklemens** [comment]
@dheideman I would add a comment/note/warning on why you can't plug into the 3.3V power right next to the 5V power on the Arduino.

@rjehangir The rest looks good. Do you think we should retake the photos in our small photobooth?

**Comment by dheideman** [comment]
@kklemens I've clarified/elaborated on some of the explanations, including the note about the 5 V supply to the _Level Converter_, and added notes about soldering the header pins to the _Level Converter_.

I also added links to important store pages.

I will hold off on annotating the pictures until we decide what to do about the pictures themselves.  I will work on a quick 3D-printed light diffuser in the meantime.

**Comment by dheideman** [comment]
@kklemens I forgot about the links.  I feel those should be included in this PR.

Other than the Bar30 page, where do we want to add links?

**Comment by dheideman** [comment]
I plan to look at lights for taking nicer pictures this weekend.  If the current pictures are sufficient in the interim, I am comfortable with merging this branch (once the links have been handled) and I can put in a PR for improved pictures at a later date.

**Comment by rjehangir** [comment]
@dheideman We reviewed this with everyone today and have some more feedback. First off, we're thinking that we might get a consistent background to use for all tutorials, maybe a nice wooden cutting board or something that will be consistent. That coupled with a few lights would provide some consistency between you and us.

Also, there is some example Arduino code on the main Bar30 docs page right now. I think we should merge that into your tutorial and eliminate it from the page (and eliminate the page altogether eventually). I think having the base example code on your tutorial would be nice anyways.

Here's where that is right now: http://docs.bluerobotics.com/bar30/#arduino

Can you work on that and the pictures?

**Pull request merged**
