### PR TITLE
Add redirection to new docs

### PR DESCRIPTION
**Pull request by Williangalvani**
This redirects pages with `redirect: <url>` in the markdown to the url indicated and adds a notice before the content: 
image

### CODE REVIEW

**Comment by rjehangir** [comment]
Looking good but I want @kklemens to review as well.

@Williangalvani Nicely implemented.

**Comment by jaxxzer** [comment]
:shipit:

**Comment by jaxxzer** [comment]
@kklemens this is what it will look like:
image


and this old page will automatically redirect to the new page here: https://www.bluerobotics.com/store/rov/bluerov2/bluerov2/

**Comment by Williangalvani** [comment]
This is an example for the brov2 only, after the PR is accepted I'll check the other products one by one.

**Comment by kklemens** [comment]
@Williangalvani So it will be an automatic redirect after a few seconds? I'm ok with that.

I don't *think* we will need it, but would there be a way to stop the re-direct if needed?

**Comment by Williangalvani** [comment]
> I don't _think_ we will need it, but would there be a way to stop the re-direct if needed?

Apparently you can't cancel it. 

I've been reading about redirects and SEO, apparently the best option would be to use a HTTP 301 redirect.

@jaxxzer is this hosted in gh-pages or similar? Then the meta refresh is probably the best way to go.

**Comment by Williangalvani** [comment]
This last commit should help with SEO too by helping the search engines know the new links are the "real" ones.

**Comment by Williangalvani** [comment]
So, @rjehangir confirmed these docs are hosted in gh-pages, so this is the way to go.
I went through the files and redirect them to their counterparts in the new website.

I noticed that for some of my searches the old page was higher ranked than the new one, so hopefully this helps with the SEO too.

@jaxxzer and @kklemens you may want to take another look before merging, I added the redirect to the remaining products.

**Comment by kklemens** [comment]
@Williangalvani I can't access anything on the docs site on this restricted Wifi in the UK, so whatever you and @rjehangir feel comfortable with.

**Pull request merged**
